config/routes.rb
Rails.application.routes.draw do
  root "cars#index"

  resources :pilots
  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  include Validatable
end

app/models/concerns/validatable.rb
module Validatable
  extend ActiveSupport::Concern

  included do
    validates :name, :document, presence: true
  end
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  include Validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include Filterable
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = filter_by_color
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:name, :model, :color, :document)
    end
end

app/controllers/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  def filter_by_color
    Car.where.not(color: 'White')
  end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: %i[ show edit update destroy ]

  # GET /pilots or /pilots.json
  def index
    @pilots = Pilot.all
  end

  # GET /pilots/1 or /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots or /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to pilot_url(@pilot), notice: "Pilot was successfully created." }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1 or /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to pilot_url(@pilot), notice: "Pilot was successfully updated." }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1 or /pilots/1.json
  def destroy
    @pilot.destroy

    respond_to do |format|
      format.html { redirect_to pilots_url, notice: "Pilot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pilot_params
      params.require(:pilot).permit(:name, :document)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Name:</strong>
    <%= car.name %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= car.document %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :document, style: "display: block" %>
    <%= form.text_field :document %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcernsUsage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pilots/_form.html.erb
<%= form_with(model: pilot) do |form| %>
  <% if pilot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
        <% pilot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :document, style: "display: block" %>
    <%= form.text_field :document %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pilots/_pilot.html.erb
<div id="<%= dom_id pilot %>">
  <p>
    <strong>Name:</strong>
    <%= pilot.name %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= pilot.document %>
  </p>

</div>

app/views/pilots/edit.html.erb
<h1>Editing pilot</h1>

<%= render "form", pilot: @pilot %>

<br>

<div>
  <%= link_to "Show this pilot", @pilot %> |
  <%= link_to "Back to pilots", pilots_path %>
</div>

app/views/pilots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pilots</h1>

<div id="pilots">
  <% @pilots.each do |pilot| %>
    <%= render pilot %>
    <p>
      <%= link_to "Show this pilot", pilot %>
    </p>
  <% end %>
</div>

<%= link_to "New pilot", new_pilot_path %>

app/views/pilots/new.html.erb
<h1>New pilot</h1>

<%= render "form", pilot: @pilot %>

<br>

<div>
  <%= link_to "Back to pilots", pilots_path %>
</div>

app/views/pilots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pilot %>

<div>
  <%= link_to "Edit this pilot", edit_pilot_path(@pilot) %> |
  <%= link_to "Back to pilots", pilots_path %>

  <%= button_to "Destroy this pilot", @pilot, method: :delete %>
</div>